version: "3"

services:
  backend:
    image: i-iot-backend
    deploy:
      replicas: 1
    build: 
      context: ./
      dockerfile: ./iot-backend/Dockerfile
    volumes:
      - ./iot-backend:/iot-project/iot-backend
    networks:
      - iot-network
  frontend:
    build: ./iot-frontend
    volumes:
      - ./iot-frontend:/var/www/iot-app/
    networks:
      - iot-network
  nginx:
    image: nginx
    deploy:
      replicas: 1
    networks:
      - iot-network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./iot-frontend/build:/var/www/iot-app/
    depends_on:
      - backend
      - frontend
networks:
  iot-network:
